# Generated by Django 3.1.2 on 2020-10-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_text', models.CharField(max_length=50)),
                ('subtitulo_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosotros_text', models.CharField(max_length=25)),
                ('descripcion_text', models.TextField(max_length=350)),
                ('nosotros_image', models.ImageField(default='404.png', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_text', models.CharField(max_length=25)),
                ('precio_int1', models.IntegerField()),
                ('post_text1', models.CharField(max_length=30)),
                ('descripcion_text1', models.TextField(max_length=175)),
                ('post_image1', models.ImageField(default='404.png', upload_to='images')),
                ('precio_int2', models.IntegerField()),
                ('post_text2', models.CharField(max_length=30)),
                ('descripcion_text2', models.TextField(max_length=175)),
                ('post_image2', models.ImageField(default='404.png', upload_to='images')),
                ('precio_int3', models.IntegerField()),
                ('post_text3', models.CharField(max_length=30)),
                ('descripcion_text3', models.TextField(max_length=175)),
                ('post_image3', models.ImageField(default='404.png', upload_to='images')),
            ],
        ),
    ]
