# Generated by Django 3.1.2 on 2020-11-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('mensaje', models.TextField(max_length=350)),
            ],
        ),
    ]
