# Generated by Django 3.1.2 on 2020-11-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0003_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripcion_text1',
            new_name='descripcion_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_image1',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text1',
            new_name='post_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='precio_int1',
            new_name='precio_int',
        ),
        migrations.RemoveField(
            model_name='post',
            name='descripcion_text2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='descripcion_text3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_text2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_text3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='precio_int2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='precio_int3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='promo_text',
        ),
    ]
