# Generated by Django 3.1.2 on 2020-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0004_auto_20201104_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Describe tu experiencia en una palabra', max_length=10)),
                ('calificacion', models.IntegerField(choices=[[0, '⭐⭐⭐⭐⭐'], [1, '⭐⭐⭐⭐'], [2, '⭐⭐⭐'], [3, '⭐⭐'], [4, '⭐']], default=0)),
                ('mensaje', models.TextField(help_text='Describenos tu experiencia con nuestros servicios', max_length=350)),
            ],
        ),
        migrations.RenameField(
            model_name='header',
            old_name='subtitulo_text',
            new_name='header_text',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='titulo_text',
            new_name='header_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='descripcion_text',
            new_name='post_descripcion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='precio_int',
            new_name='post_precio',
        ),
    ]
