# Generated by Django 3.1.2 on 2020-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0005_auto_20201104_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='calificacion',
            field=models.IntegerField(choices=[[0, '⭐⭐⭐⭐⭐'], [1, '⭐⭐⭐⭐'], [2, '⭐⭐⭐'], [3, '⭐⭐'], [4, '⭐']]),
        ),
    ]
