# Generated by Django 3.1.2 on 2020-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0006_auto_20201104_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
