# Generated by Django 3.1.2 on 2020-11-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0007_auto_20201104_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
