# Generated by Django 3.1.2 on 2020-11-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0008_auto_20201104_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='nombre',
        ),
    ]
