# Generated by Django 3.1.2 on 2020-11-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0009_remove_experiencia_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiencia',
            new_name='Experiencias',
        ),
    ]
