# Generated by Django 3.1.2 on 2020-11-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0010_auto_20201104_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='header_autor',
            field=models.CharField(default=123, max_length=25),
            preserve_default=False,
        ),
    ]
