# Generated by Django 3.1.2 on 2020-11-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0011_header_header_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_text',
            field=models.TextField(max_length=150),
        ),
    ]
