# Generated by Django 3.1.2 on 2020-11-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0012_auto_20201104_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nosotros',
            name='descripcion_text',
        ),
        migrations.AddField(
            model_name='nosotros',
            name='nosotros_title',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='nosotros_text',
            field=models.TextField(max_length=350),
        ),
    ]
