# Generated by Django 3.1.2 on 2020-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0013_auto_20201104_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='mensaje',
            field=models.TextField(help_text='Describenos tu experiencia con OnBreak', max_length=350),
        ),
    ]
