# Generated by Django 3.1.2 on 2020-11-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0014_auto_20201105_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='nosotros_autor',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
