# Generated by Django 3.1.2 on 2020-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0015_nosotros_nosotros_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_autor',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='calificacion',
            field=models.IntegerField(choices=[[0, ' ★ ★ ★ ★ ★'], [1, ' ★ ★ ★ ★'], [2, ' ✭ ✭ ✭'], [3, ' ✭ ✭'], [4, ' ✭⭐']]),
        ),
    ]
