# Generated by Django 3.1.2 on 2020-11-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0016_auto_20201105_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_descripcion',
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(max_length=175),
        ),
    ]
