# Generated by Django 3.1.2 on 2020-11-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardwebsite', '0017_auto_20201105_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='calificacion',
            field=models.IntegerField(choices=[[0, ' ★ ★ ★ ★ ★'], [1, ' ★ ★ ★ ★'], [2, ' ★ ★ ★'], [3, ' ★ ★'], [4, ' ★']]),
        ),
    ]
